"""empty message

Revision ID: 26be994604e9
Revises: 4ccf99e567ac
Create Date: 2021-03-17 19:00:41.757444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26be994604e9'
down_revision = '4ccf99e567ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_groups',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('asset_group_members',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('asset_uuid', postgresql.UUID(), nullable=False),
    sa.Column('group_uuid', postgresql.UUID(), nullable=False),
    sa.Column('activation_time', postgresql.TIMESTAMP(), server_default=sa.text('(now() at time zone \'utc\')'), nullable=False),
    sa.Column('deactivation_time', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uuid'], ['assets.uuid'], ),
    sa.ForeignKeyConstraint(['group_uuid'], ['asset_groups.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_asset_group_members_asset_uuid'), 'asset_group_members', ['asset_uuid'], unique=False)
    op.create_index(op.f('ix_asset_group_members_group_uuid'), 'asset_group_members', ['group_uuid'], unique=False)
    op.drop_table('identifiers')
    op.drop_table('idtypes')
    # op.drop_index('ix_identifiers_asset', table_name='identifiers')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identifiers',
    sa.Column('id_str', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('asset', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset'], ['assets.uuid'], name='identifiers_asset_fkey'),
    sa.ForeignKeyConstraint(['type'], ['idtypes.typename'], name='identifiers_type_fkey'),
    sa.PrimaryKeyConstraint('id_str', name='identifiers_pkey'),
    sa.UniqueConstraint('asset', 'type', name='identifiers_asset_type_key')
    )
    op.create_index('ix_identifiers_asset', 'identifiers', ['asset'], unique=False)
    op.create_table('idtypes',
    sa.Column('typename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('regex', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('typename', name='idtypes_pkey')
    )
    op.drop_index(op.f('ix_asset_group_members_group_uuid'), table_name='asset_group_members')
    op.drop_index(op.f('ix_asset_group_members_asset_uuid'), table_name='asset_group_members')
    op.drop_table('asset_group_members')
    op.drop_table('asset_groups')
    # ### end Alembic commands ###
