"""empty message

Revision ID: 393ca16153a0
Revises: 
Create Date: 2019-06-14 23:34:29.414258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '393ca16153a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('subject_type', postgresql.ENUM('assets', 'attributes', 'relations', 'classes', 'identifiers', name='subjecttype'), nullable=False),
    sa.Column('subject', postgresql.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('create', 'update', 'delete', 'enable', 'disable', name='activitytype'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('assetclasses',
    sa.Column('classname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('classname')
    )
    op.create_table('assets',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('attributetypes',
    sa.Column('typename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('unique', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('typename')
    )
    op.create_table('idtypes',
    sa.Column('typename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('regex', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('typename')
    )
    op.create_table('relationtypes',
    sa.Column('typename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('unique_src', sa.BOOLEAN(), nullable=False),
    sa.Column('unique_dst', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('typename')
    )
    op.create_table('assetclass_members',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('asset', postgresql.UUID(), nullable=False),
    sa.Column('class', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['asset'], ['assets.uuid'], ),
    sa.ForeignKeyConstraint(['class'], ['assetclasses.classname'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('asset', 'class')
    )
    op.create_index(op.f('ix_assetclass_members_asset'), 'assetclass_members', ['asset'], unique=False)
    op.create_index(op.f('ix_assetclass_members_class'), 'assetclass_members', ['class'], unique=False)
    op.create_table('attributes',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('original', postgresql.UUID(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('asset', postgresql.UUID(), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['asset'], ['assets.uuid'], ),
    sa.ForeignKeyConstraint(['original'], ['attributes.uuid'], ),
    sa.ForeignKeyConstraint(['type'], ['attributetypes.typename'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_attributes_asset'), 'attributes', ['asset'], unique=False)
    op.create_table('identifiers',
    sa.Column('id_str', sa.VARCHAR(length=40), nullable=False),
    sa.Column('asset', postgresql.UUID(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['asset'], ['assets.uuid'], ),
    sa.ForeignKeyConstraint(['type'], ['idtypes.typename'], ),
    sa.PrimaryKeyConstraint('id_str'),
    sa.UniqueConstraint('asset', 'type')
    )
    op.create_index(op.f('ix_identifiers_asset'), 'identifiers', ['asset'], unique=False)
    op.create_table('relations',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('original', postgresql.UUID(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('asset_src', postgresql.UUID(), nullable=False),
    sa.Column('asset_dst', postgresql.UUID(), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('asset_src != asset_dst'),
    sa.ForeignKeyConstraint(['asset_dst'], ['assets.uuid'], ),
    sa.ForeignKeyConstraint(['asset_src'], ['assets.uuid'], ),
    sa.ForeignKeyConstraint(['original'], ['relations.uuid'], ),
    sa.ForeignKeyConstraint(['type'], ['relationtypes.typename'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_relations_asset_dst'), 'relations', ['asset_dst'], unique=False)
    op.create_index(op.f('ix_relations_asset_src'), 'relations', ['asset_src'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relations_asset_src'), table_name='relations')
    op.drop_index(op.f('ix_relations_asset_dst'), table_name='relations')
    op.drop_table('relations')
    op.drop_index(op.f('ix_identifiers_asset'), table_name='identifiers')
    op.drop_table('identifiers')
    op.drop_index(op.f('ix_attributes_asset'), table_name='attributes')
    op.drop_table('attributes')
    op.drop_index(op.f('ix_assetclass_members_class'), table_name='assetclass_members')
    op.drop_index(op.f('ix_assetclass_members_asset'), table_name='assetclass_members')
    op.drop_table('assetclass_members')
    op.drop_table('relationtypes')
    op.drop_table('idtypes')
    op.drop_table('attributetypes')
    op.drop_table('assets')
    op.drop_table('assetclasses')
    op.drop_table('activity')
    # ### end Alembic commands ###
