"""empty message

Revision ID: cf316a537584
Revises: 393ca16153a0
Create Date: 2019-06-26 16:33:29.921704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf316a537584'
down_revision = '393ca16153a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('time', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('activity', sa.Column('user', sa.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'user')
    op.drop_column('activity', 'time')
    # ### end Alembic commands ###
