"""empty message

Revision ID: 2953ff0903cf
Revises: d2f8fc00380a
Create Date: 2019-08-08 13:45:58.724881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2953ff0903cf'
down_revision = 'd2f8fc00380a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('row', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('time_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('host', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['row'], ['data.uuid'], name='sync_row_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='sync_pkey')
    )
    # ### end Alembic commands ###
