"""empty message

Revision ID: 40c6e1f98cc2
Revises: e04046339dba
Create Date: 2019-06-17 09:29:52.252501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40c6e1f98cc2'
down_revision = 'e04046339dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('time_utc', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('time_mono', sa.BIGINT(), nullable=True),
    sa.Column('rcvtime_utc', postgresql.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('rcvtime_mono', sa.BIGINT(), nullable=False),
    sa.Column('source', postgresql.UUID(), nullable=True),
    sa.Column('asset', postgresql.UUID(), nullable=True),
    sa.Column('rcvnode', postgresql.UUID(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['datatypes.typename'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
