"""empty message

Revision ID: 804ff7ef43e5
Revises: 40c6e1f98cc2
Create Date: 2019-07-05 11:48:45.803116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '804ff7ef43e5'
down_revision = '40c6e1f98cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data', 'source',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data', 'source',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
