"""empty message

Revision ID: 8145b36c4464
Revises: 895bfda5900c
Create Date: 2021-06-17 16:50:12.257284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8145b36c4464'
down_revision = '895bfda5900c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_quality',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('meta_source',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###

    op.execute("create schema data_raw")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_source', schema='public')
    op.drop_table('meta_quality', schema='public')
    # ### end Alembic commands ###

    op.execute("drop schema data_raw")

