"""empty message

Revision ID: 895bfda5900c
Revises: dc991cc51754
Create Date: 2019-08-28 15:35:18.660858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895bfda5900c'
down_revision = 'dc991cc51754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datatypes', sa.Column('autodiscover', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datatypes', 'autodiscover')
    # ### end Alembic commands ###
