"""empty message

Revision ID: dc991cc51754
Revises: 2953ff0903cf
Create Date: 2019-08-08 14:05:33.326684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc991cc51754'
down_revision = '2953ff0903cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('row', postgresql.UUID(), nullable=False),
    sa.Column('time_utc', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('host', sa.TEXT(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['row'], ['data.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync')
    # ### end Alembic commands ###
